comment:
  layout: "files"
  behavior: new # delete old comment and post new
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: yes      # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - master
